<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>

        <?php /* @escapeNotVerified */ echo $_menu; ?>
        <?php
        $html = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('navigation-menu')->toHtml();
        $replace = "";
        $html = preg_replace("/<ul>/",$replace,$html,1);
        $html = preg_replace("~>lu/<~",strrev($replace),strrev($html),1);
        $html = strrev($html);

        echo $html;
        ?>

        <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
    </ul>
</nav>
